### ISSUE TITLE
Error on Activation

### ISSUE THREAD

**Issue by jasonbahl** [bainternet/Admin-Page-Class#1]
I tried activating the plugin and got the following error:

Parse error: syntax error, unexpected '&', expecting T_VARIABLE or '$' in /home/content/j/a/b/jabrieske/html/amphenol/wp-content/plugins/admin-page-demo/admin-page-class/admin-page-class.php on line 1170

**Comment by bainternet** [comment]
Ummm, nope, can see it, make sure you download the latest version and report back again.

**Comment by jasonbahl** [comment]
Latest version works. Thanks!
