### ISSUE TITLE
javascript errors with datepicker in wp 3.5

### ISSUE THREAD

**Issue by gabeshaughnessy** [bainternet/Admin-Page-Class#11]
I am using admin page class in a theme and I get the following javascript errors on my admin page (using the demo fields provided here: http://en.bainternet.info/2012/my-options-panel)

error 1:
GET http://imagination-station.local/decon-staging/wp-content/themes/mothership/admin-page-class/jquery-ui.css?ver=3.5 404 (Not Found) themes.php:21

error 2:
Uncaught TypeError: Cannot read property '_selectDate' of undefined jquery-ui-timepicker-addon.js:962

error 3:
Uncaught TypeError: Object [object Object] has no method 'datepicker' Admin_Page_Class.js:258

I can confirm that the jquery-ui stylesheet is indeed at admin-page-class/jquery-ui.css. If I change lines 1213 and 1230 of admin-page-class to:
 wp_enqueue_style( 'jquery-ui-css', $plugin_path.'/css/jquery-ui.css' );
the stylesheet enqueues properly.

the other two errors I'm stumped on. any ideas?

**Comment by bainternet** [comment]
Thanks, this should be solved in 1.0.7
