### ISSUE TITLE
Extra slashes when saving text fields and textareas with apostrophes

### ISSUE THREAD

**Issue by cyberbitegroup** [bainternet/Admin-Page-Class#12]
Is there any way to fix the issue with text fields and text areas not accepting apostrophes?  On the client side I can accomplish it by using stripslashes but every time the options get resaved it adds two more slashes to that text field or text area and you have to delete them and resave it so there's only one.

Any way to make sure those are getting stripped when displaying field values so the user doesn't know what's going on?

If you do fix it let me know because I made a couple mods to the class and want to know which functions to modify.

**Comment by bainternet** [comment]
you can create your own validation class named `BF_Admin_Page_Class_Validate` and pass your validation function in the field args array ex:

First, when adding your field make sure you add a ‘validate_func‘ in the arguments array ex:

```
$options_panel->addTextarea('textarea_field_id',array(
    'name'=> 'My Textarea ',
    'std'=> 'std TEXTarea',
    'validate_func' => 'remove_extra_slashes'
));
```

Then create a class named “BF_Admin_Page_Class_Validate” with that function ex:

```
/**
 * Validation class
 * Define ALL validation methods inside this class
 * Use the names of these methods in the definition of meta boxes (key 'validate_func' of each field)
 */
class BF_Admin_Page_Class_Validate(){
   function remove_extra_slashes($value){
       // do you validation
       return stripslashes($value);
    }
}
```
