### ISSUE TITLE
Image Fields On Repeater Show 'Array'

### ISSUE THREAD

**Issue by cyberbitegroup** [bainternet/Admin-Page-Class#14]
When you use image fields on a repeater block it shows the word 'Array' instead of the image preview.  Small bug, but annoying to click the pencil to see the image again.

**Comment by bainternet** [comment]
Hum its the way it should be :)
its just the same as any other  field in a repeater block you don't see them unless you click the edit pencil. 
Or am I not understanding the issue here? If that is not it feel free to reopen.

**Comment by bainternet** [comment]
wait were and when do you see this "Array"

**Comment by brasofilo** [comment]
I just reproduced the bug.

Using the source sample code: http://pastebin.com/N4rMttLM
![Screen Shot 2012-12-22 at 5 54 29 AM](https://f.cloud.github.com/assets/1542052/28313/d5c0c1fc-4bf3-11e2-85ad-b22f4d2e7921.png)

**Comment by bainternet** [comment]
OK, so the only fields in your repeater block are images which means you don't really need to use a repeater block, instead use Plupload field.

if you have more then just an image field in the repeater block simply make sure that the image is not the first field in the block.
