### ISSUE TITLE
Color selector doesn't show saved color as color

### ISSUE THREAD

**Issue by brasofilo** [bainternet/Admin-Page-Class#15]
After saving the options, the color box doesn't show the color as background-color of the field with the hex value.
The `farbtastic` color wheel also doesn't show the saved value, displaying black instead:
![Screen Shot 2012-12-22 at 6 00 39 AM](https://f.cloud.github.com/assets/1542052/28317/975b1a42-4bf4-11e2-8593-7af036469db9.png)

Just to be clear, the values are saved but the visual representation is not there.

That's curious, because in a plugin where I use a very basic implementation of `farbtastic` this doesn't happens...

**Comment by bainternet** [comment]
I have no idea way this happens but i've added a quick fix in 1.1.1. Thanks
