### ISSUE TITLE
Language files

### ISSUE THREAD

**Issue by brasofilo** [bainternet/Admin-Page-Class#16]
Not sure how to deal with this, how do I merge my plugin lang files with APC's?

While debugging, I found an error in the function `load_textdomain()`.
The 'mo' is missing a dot: `get_locale() .'mo'` should be `get_locale() .'.mo'`

When I build my catalog, all APC strings are included, but the translations don't show up, nor from my language files neither from APC's. Mine works ok.

This is the basic structure that builds my plugin and includes APC:
https://gist.github.com/4374106

**Contribution**
Spanish and portuguese translations for APC, zip file with `es_ES.mo, es_ES.po, pt_BR.mo, pt_BR.po`:
http://cl.ly/2T2t1n3K0z1g

**Comment by bainternet** [comment]
Thanks a lot, muchas gracias, muito obrigado :100: 
Fixed Typo and added translation files.

as for translations not showing up, try moving 
`// Admin Page Class declared inside this class
require_once plugin_dir_path( __FILE__ ) . 'inc/class-admin.php';`

inside a hook like `plugins_loaded`

let me know.

**Comment by brasofilo** [comment]
Gotta admit I haven't passed the translation by a spellchecker... :+1: 

Nope, doing the `require` in the right place (thanks) doesn't bring the translation on.

Is it possible for two textdomains to co-exist in one plugin?

I thought of an optional argument to the `$config` array and use `__('Text',$this->args['textdomain'])`... But thinking better, this forces us to re-create the text strings in our own `.po`, and putting a property in the localization function seems not quite right...

**Comment by bainternet** [comment]
Yes its possible for two textdomains to co-exist in a single plugin as long as you load them correctly :)

In my local testing branch i found the problem and that was me using the url instrad of the path to the mo file.

So that is fixed (hopefully) and i'll push it soon.
Feel free to reopen if not.
