### ISSUE TITLE
Checkbox inside conditional not displaying the 'checked' state

### ISSUE THREAD

**Issue by brasofilo** [bainternet/Admin-Page-Class#20]
In the function `show_field_checkbox()`, if I change to `checked($meta, 'on', false)`, it works for Checkboxes inside Conditionals.

But, of course, this breaks the regular Checkbox. Not sure where to adjust this logic...

[edit]
It doesn't happens if the subfield is a Checkbox List.

**Comment by bainternet** [comment]
Fixed! Thanks

**Comment by brasofilo** [comment]
ah, maestro, always optimizing! 

I almost have a beta of my plugin ready to release, I'll ping you when so, and would be honored to have your opinion ;)

btw, do you know of plugins/themes that are using your class?

**Comment by bainternet** [comment]
I'd love to test your plugin.
as for who uses it some examples i know of many that use it but for custom developments from the amount of support questions i get in my inbox.

**Comment by brasofilo** [comment]
ok, mr. Ba, first public version @ https://github.com/brasofilo/many-tips-together

I still have to implement most of the validation functions and got some doubts about it, will open a specific ticket though.

Also, two modifications for which I'll open a feature request.

And finally, for me the color selectors are still overlapping, can you see that in the _Post and Page Listing_ section?
- we talked about it in #17 I believe so

cheers!

**Comment by bainternet** [comment]
Typo in css file, Fixed.
