### ISSUE TITLE
AddRoles and the 'multiple' argument

### ISSUE THREAD

**Issue by brasofilo** [bainternet/Admin-Page-Class#21]
Surely, it got Lost in Translation (: great movie, btw ;)

But item 2 of Issue [#17](https://github.com/bainternet/Admin-Page-Class/issues/17) is still there:

The function `addRoles` is dumping a notice when inside a Conditional field

> `Notice: undefined index 'multiple'`

Corrected adding the following
`$new_field = array( /*other key => values*/ , 'multiple' => false )`

**Comment by bainternet** [comment]
Thanks again.
