### ISSUE TITLE
[Feature request] Add classes to labels and name to form

### ISSUE THREAD

**Issue by brasofilo** [bainternet/Admin-Page-Class#23]
For styling purposes, it would be handy to have all `<label>` with a class name.

As for `<form>`, is it possible to add a `name` to it? 
I'm not sure if this may have any implication in the overall functioning...

I'm adding it in my working copies, so I can use a custom button to dispatch the submit action, like:
`document.formname.submit()`

**Comment by bainternet** [comment]
the `<label>` can be targeted by their parent `<div>`  with the class of `.at-label` ex:

``` css
.at-label label{
    /* css rules here */
}
```

as for form name, I'll move it to its own issue.

**Comment by brasofilo** [comment]
mmm, looks like the labels are not encapsulated in that div, not being able to target them...

My modified version 1.1.7 was rendering like this:

> ![screenshot v117](https://f.cloud.github.com/assets/1542052/45517/d69408dc-578d-11e2-8a0d-835aa5e8e57c.png)

This is a clean 1.1.8, with the `.at-label label` applied in my stylesheet:

> ![screenshot v118](https://f.cloud.github.com/assets/1542052/45523/947f680a-578e-11e2-8a59-366aa77371a5.png)

It is targeting the main title, and not the labels that you kindly inserted after my #18 
And unfortunately, there are no [parent selectors](http://css-tricks.com/parent-selectors-in-css/) in CSS ;)

**Comment by brasofilo** [comment]
OMG, you are too fast!
I'm still in 1.1.8 and there's already a **2.0**
lol 2much :100:

**Comment by bainternet** [comment]
Latest version is only 1.2.0  :) in version 2.0 i plan to merge this class with my meta box class.

as for the labels i only now see that you are talking about the checkbox list labels. I'll take a look again

**Comment by bainternet** [comment]
added
