### ISSUE TITLE
Error if no addColor defined

### ISSUE THREAD

**Issue by brasofilo** [bainternet/Admin-Page-Class#26]
I'm building a blank plugin with APC so as to start new ones with it bundled.

Can you confirm that Javascript is breaking if we don't have an `addColor` defined? 

``` js
TypeError: $(...).wpColorPicker is not a function
http://plugins.dev/wp-content/plugins/apc-base/inc/admin-page-class/js/Admin_Page_Class.js
Line 354
```

Looks like `if ($.farbtastic){ } else { $('.at-color-iris').wpColorPicker() }` is not  considering that the scripts may not have been enqueued in the function `check_field_color`.

**Comment by bainternet** [comment]
Thanks fixed.

**Comment by brasofilo** [comment]
Still experiencing this in 1.2.3

**Comment by brasofilo** [comment]
Not sure if the best way, but solved using

``` js
} else if ( $.isFunction($('.at-color-iris').wpColorPicker) ){
    $('.at-color-iris').wpColorPicker();
  }
```

**Comment by bainternet** [comment]
not need for isFunction , just a simple check if the wpColorPicker is available like this:

``` javascript
else if ( $.wpColorPicker) ){
    $('.at-color-iris').wpColorPicker();
}
```

i"ll push it again.
