### ISSUE TITLE
Use the class inside a theme

### ISSUE THREAD

**Issue by lhas** [bainternet/Admin-Page-Class#29]
That is not exactly a issue, but a comment:

The developer can use your class inside the theme folder, instead of plugin.

Just drag the folder inside the theme folder and include the class file on the functions.php.

I think that is interesting to say on the README.md of the repository. :)

Congratulations! We have a really nice (and oriented-object) job here. :+1:

**Comment by bainternet** [comment]
if you read the instruction at http://en.bainternet.info/2012/my-options-panel or look at the demo plugin you will see that  there is a parameter named 'use_with_theme'
with a comment 

```
//change path if used with theme set to true, false for a plugin or anything else for a custom path(default false).
```
