### ISSUE TITLE
Cheatin’ uh? error after update to WP 3.4

### ISSUE THREAD

**Issue by ghost** [bainternet/Admin-Page-Class#3]
I'm getting error "Cheatin’ uh?" when I try to upload image since wordpress version 3.4.

**Comment by ghost** [comment]
In Admin_Page_class.js I replaced <code>tb_show('', 'media-upload.php?post_id='+ jQuery('#post_ID').val() + '&type=image&apc=apc&TB_iframe=true');</code>

with

<code>tb_show('', 'media-upload.php?post_id=0&type=image&apc=apc&TB_iframe=true');</code>

Now it works.

**Comment by bainternet** [comment]
fixed, thanks.
