### ISSUE TITLE
Code field doesn't show up when swapping tabs.

### ISSUE THREAD

**Issue by brasofilo** [bainternet/Admin-Page-Class#32]
Hi, mister Ba :)

Finally, I've published it [in the repo](http://wordpress.org/extend/plugins/many-tips-together/).

Not sure if it could be the quantity of tabs/fields, but haven't debugged it. The behavior is the same in Chrome, Firefox and Opera:
- start the plugin in a tab that doesn't contain a Code field
- swap to other tab that contains a Code field (profile/login/maintenance)
- field shows blank
- refresh the browser
- plugin starts in the tab with the Code field
- field appears normally

Can you repro this?

saludos!

**Comment by bainternet** [comment]
Its a bug in Codemirror which is used as code editor.
I'm closing this as "Maybe Later" Once i merge all classes.

**Comment by brasofilo** [comment]
Solved with the following.  
`profile` and `logout` are the tab names where the Code field appears.

``` js
function fixCodeMirror() { $(window).resize(); }

$(".panel_menu li").bind("click", function(event){
      var who = $(this).attr('class');
      if( who.indexOf("profile") === -1 && who.indexOf("logout") === -1 )
            return;

      setTimeout( fixCodeMirror, 1000 );
});
```
