### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by vahidd** [bainternet/Admin-Page-Class#35]
Hi,
This is really the best option panel script.
Most users are using "Slightly Modded Options Framework" as their option panel framework.
I was using it too, because I did't know this class,
I have 2 suggestions for this class to be better:
  1- Is there anyway to add "Reset Options" button to option panel.
  2- It'd be nice if saving options be with ajax.

Kind Regards.

**Comment by bainternet** [comment]
nice ideas,
Maybe soon.

**Comment by brasofilo** [comment]
vahidd, I'm doing the reset with a Checkbox and adding this to the admin page: 

``` php
if( isset( $_POST['my_reset_plugin'] ) )
    delete_option( 'MyOptionName );
```
