### ISSUE TITLE
function Paragraph conflicts with addParagraph

### ISSUE THREAD

**Issue by rogerlos** [bainternet/Admin-Page-Class#39]
The useful function "Paragraph" conflicts with the also useful function "addParagraph" (the first adds a paragraph without a field wrapper, the latter adds a field wrapper).

Unfortunately my line numbers may be approximate as I've been modifying your code to remove hard-coded styles and a few other things. What needs to happen to make both functions work: change the type argument of one of the functions. I changed the "Paragraph" function's arg to "para", that's arbitrary on my part.

I commented out some arguments for clarity's sake.

~ line 693:

``` php
$skip = array('title','paragraph',/*omitted arguments*/);
```

``` php
$skip = array('title','para',/*omitted arguments*/);
```

~ line 750:

``` php
case 'paragraph':
```

``` php
case 'para':
```

~ line 943:

``` php
$args['type'] = 'paragraph';
$args['text'] = $text;
$args['id']   = 'paragraph';
```

``` php
$args['type'] = 'para';
$args['text'] = $text;
$args['id']   = 'para';
```

~ line 2200:

``` php
$skip = array('title','paragraph',/*omitted arguments*/);
```

``` php
$skip = array('title','para',/*omitted arguments*/);
```

**Comment by bainternet** [comment]
Actually the `Paragraph` method is just leftovers from older versions of this class and its there for backwards capability.

I don't use it any more and will probably deprecate it soon.

But feel free to extend the class and overwrite it with your own interpretations.
