### ISSUE TITLE
Uncheck checkbox if another is checked

### ISSUE THREAD

**Issue by inkcreativ** [bainternet/Admin-Page-Class#40]
I've tried this, whitout any result.. do you have an idea?

```

jQuery(document).ready(function ($)

{
   if (  $('input:checkbox[name=brique]').is(':checked'))
    {
       $('input:checkbox[name=blue]').attr('checked', false);
    }
});
```

**Comment by bainternet** [comment]
Hmmm use radio buttons?

**Comment by inkcreativ** [comment]
you mean i have to use radio buttons or is it a question?  :)

if not i do use checkboxes ..

**Comment by bainternet** [comment]
Without knowing what is the use case I can only suggest you use radio buttons

**Comment by inkcreativ** [comment]
ok thank you very much

**Comment by inkcreativ** [comment]
![capture decran 2013-07-24 a 12 29 13](https://f.cloud.github.com/assets/3805818/847918/8ff5e4f2-f44c-11e2-953e-e3198b2b4d0a.png)
yes works w/ radio buts but i really love the iphone style of the checkboxes is there any way to achieve the same result?

**Comment by bainternet** [comment]
You can try caching the change of the checkbox state and uncheck the others soething like:

``` javascript
jQuery(document).ready(function ($){
    $('input:checkbox[name=brique]').change(function() {
        if(this.checked) {
            $('input:checkbox[name=blue]').prop('checked', false);
        }
    }
    //and the other way around
    $('input:checkbox[name=blue]').change(function() {
        if(this.checked) {
            $('input:checkbox[name=brique]').prop('checked', false);
        }
    }
});
```

**Comment by inkcreativ** [comment]
yes .. thxs a lot ;)

2014-04-01 10:53 GMT+02:00 raz ohad notifications@github.com:

> You can try caching the change of the checkbox state and uncheck the
> others soething like:
> 
> jQuery(document).ready(function ($){
>     $('input:checkbox[name=brique]').change(function() {
>         if(this.checked) {
>             $('input:checkbox[name=blue]').prop('checked', false);
>         }
>     }
>     //and the other way around
>     $('input:checkbox[name=blue]').change(function() {
>         if(this.checked) {
>             $('input:checkbox[name=brique]').prop('checked', false);
>         }
>     }});
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/bainternet/Admin-Page-Class/issues/40#issuecomment-39183415
> .

## 

______

_INKCREATIV_  Intégration + Wordpress dev + Webdesign + Print

06 77 43 2007

---
