### ISSUE TITLE
Feature request: Remove all inline styles, replace with classes; allow custom class name to be passed as a parameter

### ISSUE THREAD

**Issue by rogerlos** [bainternet/Admin-Page-Class#41]
Just a request to remove inline styles from elements and use class names/plugin stylesheet instead. That way users can customize the look of their pages without having to edit the original framework.

In the same spirit, allow a class name to be passed to the fields. Users would then have a fine level of control over the appearance of elements (for example, different sized text input boxes).

Thanks again for the work that has gone into this.

**Comment by bainternet** [comment]
As of 1.2.9 there is almost no Inline styles and each field can have a user defined class.
