### ISSUE TITLE
Doesn't work in 3.6

### ISSUE THREAD

**Issue by jlav1n** [bainternet/Admin-Page-Class#43]
I don't see the admin panel under the Settings menu, using the class-demo plugin, in WordPress 3.6. Works fine in 3.5

**Comment by alfonsosiloniz** [comment]
I have just made a pull request to try to solve this problem.

https://github.com/bainternet/Admin-Page-Class/pull/44

live methods in jQuery are deprecated, and needed to change to on. I have tested succesfully with the image uploader, and know it works for me in WordPress 3.6

I have no tests executed for the rest of the methods.

**Comment by jlav1n** [comment]
Pull request #44 doesn't solve the issue of the admin panel not appearing under the Settings menu.

**Comment by jlav1n** [comment]
Closing because I found that the Better-WP-Security plugin caused this to not appear under the Settings menu, when the System Tweak of "Turn off file editor in WordPress Back-end" was set.
