### ISSUE TITLE
Warnings when using the Conditional fields.

### ISSUE THREAD

**Issue by engwerda** [bainternet/Admin-Page-Class#45]
I'm getting warnings when I use  the Conditional fields

Warning (9) Illegal string offset 'type' on line 2406 in file D:\www2\snippets.dev\wp-content\themes\roots\lib\admin-page-class\admin-page-class.php
Warning (9) Illegal string offset 'id' on line 1779 in file D:\www2\snippets.dev\wp-content\themes\roots\lib\admin-page-class\admin-page-class.php
Warning (9) Illegal string offset 'id' on line 1781 in file D:\www2\snippets.dev\wp-content\themes\roots\lib\admin-page-class\admin-page-class.php
Warning (19)    Illegal string offset 'type' on line 1783 in file D:\www2\snippets.dev\wp-content\themes\roots\lib\admin-page-class\admin-page-class.php
Warning (9) Illegal string offset 'id' on line 1786 in file D:\www2\snippets.dev\wp-content\themes\roots\lib\admin-page-class\admin-page-class.php
Warning (9) Illegal string offset 'type' on line 1787 in file D:\www2\snippets.dev\wp-content\themes\roots\lib\admin-page-class\admin-page-class.php
Warning call_user_func() expects parameter 1 to be a valid callback, class 'Roots_Admin_Page_Class' does not have a method 'show_field_w' on line 1787 in file D:\www2\snippets.dev\wp-content\themes\roots\lib\admin-page-class\admin-page-class.php
Warning call_user_func() expects parameter 1 to be a valid callback, class 'Roots_Admin_Page_Class' does not have a method 'show_field_l' on line 1787 in file D:\www2\snippets.dev\wp-content\themes\roots\lib\admin-page-class\admin-page-class.php
Warning call_user_func() expects parameter 1 to be a valid callback, class 'Roots_Admin_Page_Class' does not have a method 'show_field_r' on line 1787 in file D:\www2\snippets.dev\wp-content\themes\roots\lib\admin-page-class\admin-page-class.php
Warning (6) call_user_func() expects parameter 1 to be a valid callback, class 'Roots_Admin_Page_Class' does not have a method 'show_field_e' on line 1787 in file D:\www2\snippets.dev\wp-content\themes\roots\lib\admin-page-class\admin-page-class.php

This is some example code:

``` php
//Facebook
    $enable_facebook[] = $options_panel->addText( 'facebook_link', array(
        'name'     => __( 'Facebook Link: ', 'apc' ),
        'std'      => 'https://www.facebook.com/',
    ), true );

    //Conditional Facebook.
    $options_panel->addCondition( 'enable_facebook',
        array(
            'name'   => __( 'Enable Facebook? ', 'apc' ),
            'fields' => $enable_facebook,
            'std'    => false
        ) );

    //Twitter
    $enable_twitter[] = $options_panel->addText( 'twitter_link', array(
        'name'     => __( 'Twitter Link: ', 'apc' ),
        'std'      => 'http://www.twitter.com',
    ), true );

    //Conditional Twitter.
    $options_panel->addCondition( 'enable_twitter',
        array(
            'name'   => __( 'Enable Twitter? ', 'apc' ),
            'fields' => $enable_twitter,
            'std'    => false
        ) );
```

**Comment by bainternet** [comment]
I can't replicate but I'm sure you are doing something wrong .

paste all of your code including your Roots_Admin_Page_Class and I'll try to help.

closing as not an issue with the core class.
