### ISSUE TITLE
Editor field not working properly in Repeater Blocks

### ISSUE THREAD

**Issue by towfiqi** [bainternet/Admin-Page-Class#47]
When you use a wysiwyg textarea field in a repeaterblock, upon clicking the "Add New" button doesnt show the tinymce buttons. its editor stays fixed in "text" mode. When you save the settings the editor seems to show up just fine. Can you please fix this? Thanks!

**Comment by bainternet** [comment]
Editor field is not supported inside a repeater block. Yet.

**Comment by towfiqi** [comment]
Is there any possibility with the new version of wordpress?
or maybe use a different wysiwyg editor like this one:
http://jqueryte.com/demos

Right now the only framework that supports repeater field is APC. if you can fix this issue. the framework will be flawless.

Thanks.
