### ISSUE TITLE
Create options row inside wp_options database upon activation

### ISSUE THREAD

**Issue by towfiqi** [bainternet/Admin-Page-Class#48]
when you use the class with theme and then activate the theme in another wordpress installation, the theme doesn't create a demo_options row in the database, inside wp_options. but when you click the "save Options" button from theme options page, it creates it. Is there a way to create the demo_options row on activation? because if it doesnt create the row upon activation, every user has to click the save options button after activation. which is very confusing. 

I am using the latest version btw.

Thanks.

**Comment by bainternet** [comment]
You can use the `after_switch_theme` hook to check if your options are saved and if not you can save them ex:

``` php
function my_activation_function($oldname, $oldtheme=false) {
    //check if its allready saved in the db
    $theme_set = get_option('option_name');
    if ($theme_set) return;

    //if you get here then its the first time and you need to set your defult options
    $defaults = array(
        'field_id_1' => 'default value 1',
        'field_id_2' => 'default value 2',
        'field_id_3' => 'default value 3'
    );
    update_option('option_name',$defaults);
}
add_action("after_switch_theme", "my_activation_function", 10 ,  2);
```

**Comment by towfiqi** [comment]
Thanks for this. :)
if you ignore the few bugs it has, this is one of the best options frameworks out there. Please continue improving the framework.
