### ISSUE TITLE
addCheckboxList iPhone style does not work

### ISSUE THREAD

**Issue by zocoloco** [bainternet/Admin-Page-Class#49]
1. create addCheckBoxList field using key/value options array
2. test

RESULTS - displays iPhone style checkboxes, but when you click to turn one off, it does not save to the Database.

WORKAROUND:
3. now add call 'no-toggle' disabling iPhone style

RESULTS - as standard checkboxes it now functions.

**Comment by bainternet** [comment]
Can't replicate, make sure you are sing version 1.2.9 and up.
