### ISSUE TITLE
Repeater Block & Image's

### ISSUE THREAD

**Issue by dhigginbotham** [bainternet/Admin-Page-Class#5]
So I've found an interesting one:

The repeater block with an image inside will not load tb_show if there isn't another image type on one of the panels. 

So far I've narrowed it down to this: If I add an Image type on another panel, it will correct this issue.

However, when I enter more than one Repeater block (both with images) one of the Upload Image buttons breaks over into the second repeater (UI only, the ID's all match up correctly).

Thanks!

**Comment by bainternet** [comment]
Should be fixed :)   feel free to reopen if not.

**Comment by dhigginbotham** [comment]
Thanks bud!
