### ISSUE TITLE
Does not add menu

### ISSUE THREAD

**Issue by danemorgan** [bainternet/Admin-Page-Class#51]
Running WordPress version 3.8 I activated the My Admin Page Class usage demo with the class in a sub-folder of the demo plugin.

No menu showed. I altered the configuration variables to make a top level menu and still no menu appeared.

I then renamed the class folder and generated an white screen of death error, so the plugin is running and loading the class, buit it is not displaying the menu.

**Comment by Octopixell** [comment]
Ditto, followed the same steps. Can't seem to get Options Page to show up. Any ideas?

**Comment by bainternet** [comment]
Just tested and I can't replicate.
after activating the demo plugin under settings you should see a new menu "Demo admin page"
