### ISSUE TITLE
feature request for use inside a theme

### ISSUE THREAD

**Issue by OsoBear** [bainternet/Admin-Page-Class#52]
First off - great class! I appreciate your work.
As a feature request, could you provide a path option for use in a theme? For example:

'use_with_theme'    => true
'admin_page_path'   => '/lib/admin-page-class/'

and then on line 289 change it to:
$this->SelfPath = get_stylesheet_directory_uri() . $args['admin_page_path'];

This gives us the flexibility to include this class in our lib directory - or any other directory such as inc or includes, mydirectory etc.

thanks!

**Comment by bainternet** [comment]
The `use_with_theme` parameter accepts a String as well as Boolean meaning you can set the path directly ex:

``` php
$args = array(
    'use_with_theme' => get_stylesheet_directory_uri().'/lib/admin-page-class/',
    ...
);
```
