### ISSUE TITLE
Google Fonts not being called

### ISSUE THREAD

**Issue by thegregobrien** [bainternet/Admin-Page-Class#57]
Google fonts are not being called to the panel. I updated the main config array as instructed: 

$config = array(  
    'menu'           => 'settings',  
    'page_title'     => __('Demo Admin Page','apc'),  
    'capability'     => 'edit_themes',  
    'option_group'   => 'demo_options',  
    'id'             => 'admin_page',  
    'fields'         => array(),  
    'local_images'   => false,  
    'use_with_theme' => true,  
    'google_fonts' => true  
  );

Yet nothing is being shown on the panel.

**Comment by bainternet** [comment]
read this http://en.bainternet.info/my-options-panel/#comment-3458
