### ISSUE TITLE
jQuery not working as planned...

### ISSUE THREAD

**Issue by tpickett** [bainternet/Admin-Page-Class#6]
This is in response to my original question on your site:

Javascript isn’t working correctly for me. I tried using just the default theme with just your class and im still having the javascript issues…

The actual options page shows up correctly (i.e. styles, etc..) however, when i try and switch tabs, The information is placed at the bottom of the container, and the default options stay at the top right of the options page. The highrule above “Thank you for using WordPress” is in the middle of the options panel…

Any recomendations?

Here is a pastebin as requested:
http://pastebin.com/i5DaT4rx

**Comment by bainternet** [comment]
any javascript errors? also try to set `use_with_theme` to the actual path of the class` folder

**Comment by bainternet** [comment]
no answer and i cant replicate so closing.
