### ISSUE TITLE
Warning on repeater block when try to save changes

### ISSUE THREAD

**Issue by davidGeckocode** [bainternet/Admin-Page-Class#7]
Hi Ohad, i have a problem. I just install the plugin, go to the demo admin panel, edit some fields and then save changes, but the “repeater block” give me this message:

Warning: Illegal offset type in C:\xampp\htdocs\creamos\wp-content\plugins\admin-page-demo\admin-page-class\admin-page-class.php on line 1260

Any idea?

**Comment by bainternet** [comment]
fixed , thanks
