### ISSUE TITLE
WYSIWYG charset problem

### ISSUE THREAD

**Issue by i3ad** [bainternet/Admin-Page-Class#8]
Hi,

Iam having a problem regarding the WYSIWYG field in the Admin-Page-Class.

I have build 2 custom-admin-fields, one simple text-field (for a heading), and a WYSIWYG-field (for content).

When I type german Umlauts (ä, ü, ö) the simple-text-field renders these characters correctly, however the WYSIWYG is not!

When I look normally at the Page I get : 
Ã¤

When I look in the sourcecode of the website I get this :
&Atilde_;&curren_;

In the WP-Admin-field it looks like, and is just this (even in the HTML view):
ä

It should be an:
ä

As I said, everywhere else on the site the Umlauts get renderd correctly, except in the WYSIWYG field.

I dont know if its the same in your normal Meta-Box and/or Tax-Meta-Box classes, since I just use these WYSIWYG field the first time now. 

The Charset is enabled correctly in my php files and also in the WP options the UTF-8 is set.
When I look at the sourcecode it also displays the correct charset. My WP-Database is also just formated with UTF-8 (Adminer showed me this).

I can set an Umlaut directly besides the php tag to retrieve the field data, and this Umlaut is rendered OK :
ö < p > &Atilde_;&curren_;Inhalt der ersten Box </ p >

(the ö is writen directly into the sourcecode, the content inside the paragraph is from the custom field)

I tested various Browsers (FF, Chrome, Opera).

Hope you can help, thanks for your work! (and sorry for my english)

-Mo

P.S. It seems it doesnt happen on your Tax-Meta-Class, I just tried creating a WYSIWYG field there, and it renders Umlauts correct! But I didnt tried your normal Meta-Box-Class yet.

P.P.S. I just saw that you also got some translation problem with this Admin-Page. The Text on the 2 save buttons (on top and the one on the bottom) are different:
the top one says: "Save Changes",
the bottom one says: "Änderungen übernehmen" (german for save changes, here the Umlauts are also correct ;) )

I know I can edit this in "admin-page-class.php", I just wanted to point this out ;)

**Comment by bainternet** [comment]
Its kind of hard to understand from your post so I'll ask :)

can you see it correctly on the admin side (the options panel)?
can you see it correctly on the front end side (the actual site)?

how are you calling the saved wysiwyg data in the theme?

**Comment by i3ad** [comment]
Hi,
- can you see it correctly on the admin side (the options panel)?
  Yes, on the option panel it displays correctly. In the "Visuel" and the "HTML" view it displays as `ä`.
- can you see it correctly on the front end side (the actual site)?
  No, when I look at the frontpage it displays `Ã¤`.

When I look in the source-code of that frontpage it looks like `&Atilde_;&curren_;`.
- how are you calling the saved wysiwyg data in the theme?
  Like this:

```
<?php $contentone = get_option('page_options'); echo ($contentone['start_wysiwyg_one']); ?>
```

I build it like that:

```
$options_panel->addWysiwyg('start_wysiwyg_one',array('name'=> 'Inhalt der ersten Box '));
```

Some more Info:

Iam developing this site local.

Iam using your Admin-Class not as a plugin instead I use a custom path.

As I said the WYSIWYG Field in your Tax-Meta-Class works flawless. No problem here.

**Comment by i3ad** [comment]
Oh sorry, closed on accident, reopend.

**Comment by bainternet** [comment]
Try calling it and stripping slashes like this:

`<?php $contentone = get_option('page_options'); echo (stripslashes($contentone['start_wysiwyg_one'])); ?>`

and let me know

**Comment by bainternet** [comment]
Any update?

**Comment by i3ad** [comment]
Hi,

sorry for the late reply.

Iam sorry but stripping slashes does not fix this problem! 
In fact, it didnt change anything, its the exact same error as I reported above.

In the moment Iam using some other Option-Panel-Code to work around that error.
Iam using this : http://wptheming.com/options-framework-theme/

There I dont have any problems with "Umlauten", maybe you can look in that code?

Have a nice Day!

**Comment by bainternet** [comment]
Sorry,

Try html_entity_decode() instead so:
    `<?php $contentone = get_option('page_options'); echo (html_entity_decode($contentone['start_wysiwyg_one'])); ?>`

**Comment by i3ad** [comment]
Hi,

Yes this code actually works!! The “Umlaut“ now displays correctly in the frontend and in the sourcecode too!
Maybe you should note this in the wiki. 
Thanks for all your help!!

**Comment by i3ad** [comment]
Hi,

Another update : 
The “Umlauts“ (ä, ü, ö) are working now ...

BUT the ß ( &szlig ; ) is not working! 

As soon as I write an ß in any wysiwyg box (i got three in my site) and save the content, all the wysiwyg boxes (and also my normal textboxes!) Disapear. 

When I look at the sourcecode on the frontend:
Nothing is displayed, the h2 and p tags are totally empty. 

When I look in the WP backend: 
Visual and html editor: the ß get rendert as ß, not &szlig ;

**Comment by bainternet** [comment]
Well i did some research and found that you need to set the entity_encoding of the tinyMCE using a filter hook
like described here http://wordpress.org/support/topic/correct-way-to-allow-nbsp-entity-in-tinymce

and you can get the names from here http://stackoverflow.com/a/7797963/783536

**Comment by bainternet** [comment]
closed as localized!
