### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by brasofilo** [bainternet/Admin-Page-Class#9]
Hi Ohad, finally I'm taking a dive into this classy Class :) 

as I'm seriously considering rebuilding [my first plugin](http://wordpress.org/extend/plugins/many-tips-together/) options pane with it.

1)
There's a double `CloseTab()` at [line 242](https://github.com/bainternet/Admin-Page-Class/blob/master/admin-page-demo/class-usage-demo.php#L242) of the demo, is that correct? 
If so, I suppose it corresponds to the opening `OpenTabs_container()`. 

2) 
I'm not quite understanding the description of the Conditional Fields. 
You say _"use the same functions as above but add true as a last param"_. 
The `$repeater_fields[]` **also** have true as last parameter...

3)
Seems that we cannot have a proportional preview of the images. I'm removing the `data-he` attribute to achieve this.

4) **SOLVED, it is possible to override the deletion**
The `Delete Image` button is actually deleting the image from the library. IMO, this should be only a removal from the options data and leave the deletion for the Media Library.
Is it possible to intercept this Ajax call? 

thanks for sharing!
Rodolfo

**Comment by bainternet** [comment]
1)  Yep, that is correct.
2)  To add fields to a conditional or repeater blocks you use the same methods as you normally would but you add one parameter set to true ex:
to add a text field you use
    `$options_panel->addText('text_field_id',array('name'=> 'My Text ', 'std'=> 'std TEXT'));`
and if you want to use it in a conditional or repeater blocks you just add true as the last parameter
    `$fields[] = $options_panel->addText('text_field_id',array('name'=> 'My Text ', 'std'=> 'std TEXT'));`

the only difference is that the later returns the `$new_field` array and the first one don't.

3)  its not documented but you can pass `preview_height` and `preview_width` to the addImage method
ex:
    `$options_panel->addImage('image_field_id',array('name'=> 'My Image ','preview_height' => '120px', 'preview_width' => '440px'));`
And if the height is an issue you can set it to `auto` :)

4)
Its the same issue i'm currently facing in the same "issue" in [my other class](https://github.com/bainternet/Tax-Meta-Class/issues/44)
whats your take on that?

**Comment by brasofilo** [comment]
2) 
You forgot to put the `true` in your example above ;)
So, to be clear, both Repeater and Conditional have `true` as last param?

3) 
ah, the auto height, cool! 

4)
I agree with @manfer. 
The _real_ delete result was a bit surprising for me. Especially because I did the first tests without uploading an image and grabbed them from the Library tab. Then it was like "ups, where are my images?".

Maybe this could be solved by an extra option in `$config`, i.e., `'force_delete' => true // default false`

5) _a new one_
As I'm dealing with many options, I wanted the page to reload in the last edited tab -not in the first one.
Am [using hashes](http://pastebin.com/WwMBZteb) to achieve that. What do you think?

**Comment by brasofilo** [comment]
OMG, I wrote an extended answer an the "Comment" button evaporated with it! 
---gee, I'll wait a little bit to see if it re-incarnates... will write a summary in the notepad meanwhile

**Comment by bainternet** [comment]
2) yes.
4) i actually already updated the other class with a remove meta only and a delete image by filter hook options.
5) in my local development branch i have a solution based on cookies and i'll merge it later on :)

update:
4) done!
5) done!
:)

**Comment by brasofilo** [comment]
From 1 to 5, five stars, olé! 
:+1: 

The spam filter got my previous messages, support says I'm cleared of being a spammy suspect :100:
